# Generated by Django 3.0.5 on 2020-07-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='Anonymous', max_length=130),
        ),
    ]
